### ISSUE TITLE
Worker gets stuck picking up items

### ISSUE THREAD

**Issue by Log234** [Scarabol/ColonyConstructionMod#1]
For some reason when I place a blueprint the worker walks to the building block, walks to the crate, and then gets stuck. It doesn't appear to pick up any items.

This issue happens on fresh saves in version 1.5.

**Comment by Scarabol** [comment]
Which blueprint did you use?
Can you provide me the blueprint for debugging?

**Comment by Log234** [comment]
I renamed the file to .txt so that Github would allow it, it was naturally a .json file.
[house.txt](https://github.com/Scarabol/ColonyConstructionMod/files/1253198/house.txt)

The issue is however not isolated to a single blueprint but rather occurs for all I have tested so far.

**Comment by Scarabol** [comment]
We need more details about this issue.

1. Did you have some chat messages like "Bob here from site at ..."?

2. Please check if your savegame folder contains a "blocktypes" folder and if this folder contains any files, which name starts with "mods.scarabol.construction.blueprints." and post them here, pls.

**Comment by Log234** [comment]
1) I did not have any chat messages at all.
2) The folder contained this file:
[mods.scarabol.construction.blueprints.house.txt](https://github.com/Scarabol/ColonyConstructionMod/files/1253863/mods.scarabol.construction.blueprints.house.txt)
(Again renamed to ".txt")

**Comment by Log234** [comment]
I downloaded the new release 2.0, and the issue appears to be fixed there.
